### ISSUE TITLE
Text boxes for keys on the manage screen are indented

### ISSUE THREAD

**Issue by cmcg513** [pWhitS/EncryptEverything#3]
In the text areas for the keys in the manage screen, there is some initial indentation for some reason.

**Comment by pWhitS** [comment]
Sometimes it happens for me and sometimes not. I think its a textarea thing. I puts the cursor on the first line where you click it first.

**Comment by cmcg513** [comment]
I actually fixed this in commit b3f75dd3da4d5233fdff094db4d2e955172770af
It was because there was whitespace between the opening and closing textarea tags
